#!/usr/bin/env bash
set -euo pipefail
#
# Mimir server self-update (GitOps-style). Run by mimir-update.timer.
#
#   1. git pull this repo (fast-forward only)
#   2. render image tags from ../versions.yml into .env.versions
#   3. docker compose pull && up -d (no-op when nothing changed)
#
# Manual run:  bash /opt/mimir/mimir-release/deploy/mimir-update.sh
# Hold a box:  systemctl disable --now mimir-update.timer

cd "$(dirname "${BASH_SOURCE[0]}")"
REPO_DIR="$(cd .. && pwd)"

CHANNEL="${MIMIR_CHANNEL:-$(grep -E '^MIMIR_CHANNEL=' .env 2>/dev/null | cut -d= -f2 || true)}"
CHANNEL="${CHANNEL:-stable}"

echo "[mimir-update] pulling ${REPO_DIR} (channel: ${CHANNEL})"
git -C "$REPO_DIR" pull --ff-only --quiet || {
  echo "[mimir-update] WARNING: git pull failed (offline?); continuing with current manifest"
}

# --- render versions.yml -> .env.versions ---
SERVER_TAG=$(awk -v ch="$CHANNEL" '
  $0 ~ "^"ch":" {f=1; next}
  /^[^[:space:]]/ {f=0}
  f && /server:/ {gsub(/#.*/,""); print $2; exit}
' "$REPO_DIR/versions.yml")

DISPLAY_VERSION=$(awk -v ch="$CHANNEL" '
  $0 ~ "^"ch":" {f=1; next}
  /^[^[:space:]]/ {f=0}
  f && /display-client:/ {gsub(/#.*/,""); print $2; exit}
' "$REPO_DIR/versions.yml")

[ -n "$SERVER_TAG" ] || { echo "[mimir-update] ERROR: no server tag for channel '$CHANNEL' in versions.yml"; exit 1; }
[ "$SERVER_TAG" != "v0.0.0" ] || { echo "[mimir-update] versions.yml still has placeholder v0.0.0 — nothing to deploy yet"; exit 0; }

cat > .env.versions <<EOF
# Generated by mimir-update.sh from versions.yml — do not edit.
MIMIR_SERVER_TAG=${SERVER_TAG}
MIMIR_DISPLAY_VERSION=${DISPLAY_VERSION:-}
EOF
echo "[mimir-update] server=${SERVER_TAG} display-client=${DISPLAY_VERSION:-n/a}"

# --- converge ---
docker compose --env-file .env --env-file .env.versions pull --quiet
docker compose --env-file .env --env-file .env.versions up -d --remove-orphans

# Clean up superseded images (keeps the currently-running ones).
docker image prune -f >/dev/null

echo "[mimir-update] done"
